### ISSUE TITLE
 ReflectionException: Class config does not exist

### ISSUE THREAD

**Issue by brazorf** [orchestral/testbench#132]
I had a working set of passing unit tests, all of them extending PHPUnit base class.

Next, i need to test the database access so i am installing this package. I've added the following class:

```php
<?php namespace Foothing\Tests\Laravel\Visits\Repositories;

class VisitRepositoryTest extends \Orchestra\Testbench\TestCase {

    public function setUp() {
        parent::setUp();

        $this->loadMigrationsFrom([
            '--database' => 'testing',
            '--realpath' => realpath(__DIR__.'/../../src/migrations'),
        ]);
    }

    protected function getEnvironmentSetUp($app) {
        $app['config']->set('database.default', 'testing');

        $app['config']->set('database.connections.testing', [
            'driver'   	=> 'mysql',
            'host' 		=> 'localhost',
            'database' 	=> 'pageviews',
            'username'	=> 'pageviews',
            'password'	=> 'pageviews',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ]);
    }

    function testFoo() {}

    public function tearDown() {
        parent::tearDown();
    }

}
```

After i'ìve added this to my phpunit suite, all other tests are broken and they are raising the following error:

```
10) Foothing\Tests\Laravel\Visits\VisitsTest::test_trackable_return_true_when_no_rules
ReflectionException: Class config does not exist
```

The test in error is something like this:

```php
public function test_trackable_return_true_when_no_rules() {
        Config::shouldReceive('get')->once()->with('visits.enabled')->andReturn(true);
        Config::shouldReceive('get')->once()->with('visits.rules')->andReturnNull();
        $this->assertTrue($this->visits->trackable($this->request));
}
```

And the Config facade is imported like this: `use Illuminate\Support\Facades\Config`

If i do exclude the Testbench test case, the suite is working again.

Why is this happening?

**Comment by brazorf** [comment]
Ok i got that the Facade alias is missing, so i've added the following: 

```php
protected function getPackageAliases($app) {
        return [
            'config' => 'Illuminate\Config\Repository'
        ];
}
```

However, i still have a question: isn't this package supposed to bootstrap all of the Laravel stuff, like aliases? Did i forget to configure something, or the actual solution is adding the alias myself?

**Comment by crynobone** [comment]
Can you make a PR to replicate the failing test, our current `tests` are already testing for facade alias.

**Comment by brazorf** [comment]
Just get this https://github.com/foothing/laravel-simple-pageviews/releases/tag/0.3.0

Then comment out the `getPackageAliases` method, and the tests will fail.

**Comment by crynobone** [comment]
Can you create a failing test case on **this** repository?

I don't have the time duplicating these issue.

**Comment by crynobone** [comment]
Added the test 996bb94 and the testsuite is green https://travis-ci.org/orchestral/testbench/builds/166187459

Marking this is `wontfix` until a replicable tests is added to this repo.

**Comment by kmuenkel** [comment]
Your issue sounds slightly different from what I just encountered, but something like this may be a factor: https://stackoverflow.com/questions/49093727/laravel-5-5-phpunit-with-coverage-doesnt-like-routes-from-multiple-files-and
Easy way to tell is if your tests run properly without code-coverage. In my case, the error I got back was "a facade root has not been set" because I was using a ServiceProvider to load new Routes. If that's the case, the fault would be in the phpunit.xml configuration or directory setup, not Testbench.

Laravel Apps avoid the issue altogether by placing routes in a separate folder, but those who develop Composer packages might be more inclined to place such procedural files it somewhere instead inside `src` instead. Meaning the symptoms would most commonly show up via Testbench, but not making it the culprit.
