### ISSUE TITLE
The "--realpath" option does not exist.

### ISSUE THREAD

**Issue by z1haze** [orchestral/testbench#156]
Hey, I have been using this package for a about 2 weeks or so now, and its really awesome. Today I have made from pretty massive changes in my project and went to run my tests again, and everything is failing miserable throwing this same error.

`Symfony\Component\Console\Exception\InvalidOptionException: The "--realpath" option does not exist.`

Can you possibly have an idea what could be causing this? Clearly the option does exist because its been working for a while now.. What could I have changed that would make it break though?

**Comment by z1haze** [comment]
I think I see what has happened, I've updated and broke my code due to your update.. It says use loadMigrationsFrom() now, which I am actually using on my service provider, but I do not understand how to make that happen from the test case

**Comment by z1haze** [comment]
i also tried pulling in orchestra/database and it still fails with same error

**Comment by crynobone** [comment]
Read the readme! Look at the example tests in Testbench.

**Comment by z1haze** [comment]
this is how you treat people who cant figure out your package? sweet

**Comment by crynobone** [comment]
This is how I treat repeated question which you can find from closed issue, reading the readme.

First, you guys keep asking for stable Testbench to test on Laravel 5.4 when it can be done in months without a stable tag, then you guys argue about `orchestra/database` not being stable, so I made it optional and took the time to update README, CHANGELOG and what not. 

https://github.com/orchestral/testbench/issues/155
https://github.com/orchestral/testbench/issues/153
https://github.com/orchestral/testbench/issues/146
https://github.com/orchestral/testbench/issues/145
https://github.com/orchestral/testbench/issues/143
https://github.com/orchestral/testbench/issues/142
https://github.com/orchestral/testbench/issues/155
https://github.com/orchestral/testbench/issues/153

So seriously, read the whole thing properly, if you don't get it, the example in the `tests` folder. If you think the readme need to be tweak to make it easier to understand, feel free to send in a Pull Request.

**Comment by z1haze** [comment]
Yea, and if you read me what said, i didnt require the database package and it still said that the --realpath did not work.. but whatever man

**Comment by z1haze** [comment]
But its fine, i did it the loadMigrationsFrom() way.. i just had to remove my if running in console check.

**Comment by crynobone** [comment]
If you have read the readme before asking about this, you would see the following words.

![screen shot 2017-02-08 at 9 49 25 am](https://cloud.githubusercontent.com/assets/172966/22720118/f626bf1e-ede3-11e6-90d3-bf76d8dd3930.png)

**Comment by z1haze** [comment]
i guess i dont know what that means. im still new to this stuff

**Comment by luiz-brandao** [comment]
Hi @crynobone, first I would like to thank you for dedicating your time to this package. Second, I would like to give my two cents regarding this issue with realpath. 

Sometimes when people keep asking the same question, over and over again, it means things might not be as clear as we think they are. I'm saying that because I'm another one to stumple upon this problem. Even after reading everything (examples and what not) it wasn't clear what I was doing wrong, although I finally figure it out in the end.

I think the readme is a bit confusing because it seems to have some conflicting information. It tells you to use `ServiceProvider::loadMigrationsFrom()` but right after it gives you an example with `--realpath`. People will jump right to that example, since the code is staring them in the face. And then if you read it more carefully you find the warning about it being deprecated. AFAIK something deprecated is supposed to work nonetheless, but in this case it doesn't.

You might have a reason to keep that section there, but if not, my suggestion would be to remove the `Realpath Migration` section from the Readme altogether or at least make it more obvious that we should not be using it. I could make a Pull Request if you think it would be useful.

PS: I understand it can be frustrating dealing with the same questions all the time, but not everybody is lazy, so no need to be rude ;)

**Comment by crynobone** [comment]
@luiz-brandao See my response on https://github.com/orchestral/testbench/issues/175#issuecomment-301305356

**Comment by luiz-brandao** [comment]
@crynobone thanks

**Comment by olavoasantos** [comment]
Hey guys. Sorry to bring this up again.

I wanted to use certain migrations only for testing purposes and I stumbled upon this problem as well.

I tried to solve this by adding the following function (which I adapted from laravel's ServiceProvider) to the TestCase class:

```php
protected function loadMigrationsFrom($paths) {
	$paths = (is_array($paths)) ? $paths : [$paths];
	$this->app->afterResolving('migrator', function ($migrator) use ($paths) {
		foreach ((array) $paths as $path) {
			$migrator->path($path);
		}
        });
}
```

Then on your TestCase setUp method you can call `loadMigrationsFrom` followed by the `artisan('migrate')` command. It worked for me. If anybody wants to give it a try.
