### ISSUE TITLE
Is it posible to seed?

### ISSUE THREAD

**Issue by xoco70** [orchestral/testbench#162]
I'm using : 

´´´
        $this->artisan('migrate', [
            '--realpath' => realpath(__DIR__ . '/../database/migrations'),
        ]);
        $this->artisan('db:seed');

´´´

but db:seed doesn't take a realpath argument

So, I get : 
`ReflectionException: Class DatabaseSeeder does not exist`

**Comment by crynobone** [comment]
You should be able to do

```php
$this->artisan('db:seed', '--class' => 'YourPackageSeederClass']);
```

But I never finds a good reason to have db seed for packages, because once you set a seed, there no way for you to add more seed data to it and have it seeded on anyone that already using your packages.  You existing users need to flush the table and reseed again, which isn't ideal.

**Comment by xoco70** [comment]
Yes, I see your point... Maybe to seed reference tables if needed

**Comment by andrewmclagan** [comment]
Or to seed test data?

**Comment by crynobone** [comment]
> Or to seed test data?

See [above answer](#issuecomment-279878715).

**Comment by andrewmclagan** [comment]
@crynobone This works fine. Was just commenting on possible use cases for seeding. We seed our SQLite database with test mocks.
