### ISSUE TITLE
Setting Config Values Before `RegisterProviders`

### ISSUE THREAD

**Issue by fulopattila122** [orchestral/testbench#179]
Hello,

I am creating test suites for packages that require access to specific config values as early as during the [registration of the provider](https://github.com/orchestral/testbench/blob/3.4/src/Traits/CreatesApplication.php#L100). In the real application this approach works since the config files are already parsed at that point.
As far as I understand, in testbench config values are intented to be set in the `getEnvironmentSetUp()` method which is exactly one step later than I'd need it.
I've seen that testbench uses a custom [LoadConfiguration](https://github.com/orchestral/testbench/blob/3.4/src/Bootstrap/LoadConfiguration.php#L52) implementation that only parses the predefined config files shipping with testbench package itself.

My question is that if I'd submit a PR that allows setting config values even before `getEnvironmentSetUp()`, would you accept it? If yes, what would be the proposed way?
- setting additional config files within the actual tests folder? (eg. `fixtures/config/*.php`)
- setting config values with another method similar to `getPackageProviders()`? (eg. `getConfigValues()`)
- setting values via a protected array? (eg. `protected $config = ['key.name' => 'value', ...];`
- somewhere else?

Thanks in advance 🙇

**Comment by crynobone** [comment]
> would you accept it? If yes, what would be the proposed way?

No, I would not.

While yes Configuration technically available before `RegisterProviders` bootstrap class, however configuration should only be accessed from within the binding callback, such as:

```php
public function register() {
    // dont access config() here.

    $this->app->bind('foo', function ($app) {
        return new Foo(config('foo')); // do it here.
    });
}
```

By doing this, it's allow Laravel to first go through every `register` method in the loaded Service Provider and allow one service provider to set a new configuration value if it needs it (one package depending on another package and need to set some config for the other package).

If you pull the config value before the binding, any overwrite value to `config()` will be ignored since it will use the cached value earlier.

If you really still want to do this, just extends `TestCase::resolveApplicationConfiguration()` method (see <https://github.com/orchestral/testbench/blob/3.4/src/Traits/CreatesApplication.php#L134>).

**Comment by fulopattila122** [comment]
Cool, extending `resolveApplicationConfiguration()` did do the trick. It was so obvious that I don't know how couldn't I figure it out myself.

Thanks!

**Comment by pablorsk** [comment]
You can redefine your config values only for your all TestCase, not for particular test. You only need split yout TestCase for every config.

```php
class ParticularTest extends TestCase
{
    /**
     * @param Application $app
     */
    protected function getEnvironmentSetUp($app): void
    {
        parent::getEnvironmentSetUp($app);
        $app['config']->set('app.debug', true);
    }

    public function testNewConfig(): void
    {
        // cool! new config here
        dd(config('app.debug'));
    }
}
