### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by fico7489** [orchestral/testbench#201]
You should put "phpunit/phpunit": "~4.8|~5.0" from "require-dev" to "require" for 3.2.*

**Comment by crynobone** [comment]
What's the reason for this?

**Comment by fico7489** [comment]
Because you need phpunit/phpunit for development of this package but also when you using this package as libraray, master have "phpunit/phpunit" in require.
With current composer.json you can include "orchestral/testbench" and have phpunit 6.0 installed in your project and running unit tests will producing errors event composer update passes well.

**Comment by crynobone** [comment]
* `3.2` is no longer an active development since Laravel `5.2` isn't, PHPUnit 6.0 only come out recently.
* We did move `require-dev` to `require` for `v3.5.0` since this is potentially a breaking change and not in any of the earlier releases.
* It's already on the suggested section (https://github.com/orchestral/testbench/blob/3.2/composer.json#L37).
