### ISSUE TITLE
Class `Mockery` not found 

### ISSUE THREAD

**Issue by rathesDot** [orchestral/testbench#227]
Hello,

first of all, I want to thank you for your work on this package. It helps so much in testing my own packages.

Currently, I'm trying to upgrade a package to Laravel 5.7 and therefore I upgrade testbench to 5.7. But then, when I run the tests all of them fail giving following exception

```php
Error: Class 'Mockery' not found

/Sites/packages/laravel-translatable/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:114
/Sites/packages/laravel-translatable/vendor/laravel/framework/src/Illuminate/Foundation/Testing/PendingCommand.php:168
/Sites/packages/laravel-translatable/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:42
/Sites/packages/laravel-translatable/tests/TestCase.php:27
```

I can actually fix this by running `composer require mockery/mockery`, but I shouldn't do this manually, right, as I actually don't use Mockery in my package itself.

The `setup()` of my testcase looks like this

```php
public function setUp()
{
    parent::setUp();

    Schema::create('test_models', function (Blueprint $table) {
        $table->increments('id');
        $table->string('name');
        $table->string('place');
        $table->string('title')->default('');
        $table->timestamps();
    });

    $this->artisan('migrate');

    $this->withFactories(__DIR__.'/../database/factories');
}
```

Am I missing something here, or is it actually something that should be fixed on your package side?

**Comment by rathesDot** [comment]
I noticed that Laravel itself loads mockery as a separate dev-dependency (see: https://github.com/laravel/framework/blob/5.7/composer.json#L80) ... But I think, that is going to be ignored as it is require-dev of a dependency ...

Also, I get `orchestra/testbench-core suggests installing mockery/mockery (Allow to use Mockery for testing (^1.0).)`, but for me it looks like we should add it to this packages require-dev by default.

**Comment by crynobone** [comment]
Not going to change this, the suggestion was there for this specific reason.

**Comment by amazzoccone** [comment]
I'm having the same problem 😢.

**Comment by crynobone** [comment]
When you don't want to mock the artisan command plus append the command such as `$this->artisan('migrate')->run();` as suggested from the documentation.

**Comment by unfalln** [comment]
Apologies for prolonging this, but I do not understand why this is not an issue. I have upgraded testbench 3.6 -> 3.7 and I am now getting an error with every test case that `'Mockery' is not defined` that was not thrown previously. I updated my code to replace `$this->artisan('migrate', ...);` with `$this->loadLaravelMigrations(...);` however I still get themock undefined `Mockery` class error. The only way to workaround this issue is to `composer require mockery/mockery` on each project that uses testbench.

If this is how you expect projects to be upgraded, please make this clear in the documentation. Currently the migration section of the readme is quite confusing.

**Comment by palypster** [comment]
I have **exactly** same issue and same opinion as @unfalln
