### ISSUE TITLE
Question: csrf_token() returns empty string

### ISSUE THREAD

**Issue by joshbruce** [orchestral/testbench#269]
Thanks for this.

Looking to test HTML output on a form. Form includes CSRF token.

Value of token appears to be empty string?

Is this expected?

Would presume so give it makes it so I don't have to workaround different string in my tests but didn't see it called out in the documentation.

**Comment by crynobone** [comment]
Does the route loaded with `web` (which runs `Illuminate\Session\Middleware\StartSession`) middleware?

**Comment by joshbruce** [comment]
Fair question. I'm not using `$this->visit()` - do I need to?

What I'm testing doesn't require routes and I saw something I believe in issues talking about sessions where a proposed solution was something like this:

```php
    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app);

        $app->make('Illuminate\Contracts\Http\Kernel')
            ->pushMiddleware('Illuminate\Session\Middleware\StartSession');
    }
```

But I don't recall if it mentioned using `$this->visit()` was required. Thanks!

**Comment by crynobone** [comment]
> Fair question. I'm not using $this->visit() - do I need to?

`visit()` should be part of `testbench-browser-kit` and not `testbench`. You would need that if you're doing CSS selector based interaction with the result HTML. 

Testbench execute the tests without using the default `App\Providers\RouteServiceProvider` where all `routes/web.php` request are wrapped with `web` middleware. Any route defined by packages that require session should implements `web` middleware or implements it's own equivalent, otherwise Laravel wouldn't start the session when handling the request and `csrf_token()` would then return empty string as what you're initially experiencing.

**Comment by joshbruce** [comment]
> Any route defined by packages that require session should implements web middleware or implements it's own equivalent

I'm **not** using routes. 

Is there a way to create a session that generates a result from `csrf_token()` without doing so??

The `getEnvironmentSetUp($app)` does not seem to be the way, if I'm understanding.

**Comment by joshbruce** [comment]
This seems to do the trick, in case someone stumbles here via search.

```php
use Illuminate\Support\ViewErrorBag;
use Illuminate\Support\MessageBag;

public function testSomething()
{
  // faux form error handling
  $errorBag = (new ViewErrorBag)
    ->put("default", new MessageBag([
      "{input-name}" => ["error 1", "error 1"]
    ])
  );
  session()->put("errors", $errorBag);

  // faux error submission, old value for field
  session()->put("old", ["{input-name}" => "Hello, World!"]);
}
```
